### ISSUE TITLE
Share common libraries

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1161]
Create reausable packages that can be shared between the projects.

- [x] [Share libraries between Testnet Wallet/Boutique backends](https://github.com/interledger/testnet/issues/1187)
- [x] [Share libraries between Testnet Wallet backend and frontend](https://github.com/interledger/testnet/issues/1188)
- [x] [Move Boutique controller functions to arrow functions](https://github.com/interledger/testnet/issues/1189)
- [ ] Share UI libraries
