### ISSUE TITLE
Share libraries Wallet <-> Boutique

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1187]
Share libraries between Testnet Wallet backend and Testnet Boutique backend.
Identified shareable locations:
- [x]  [config/logger](https://github.com/interledger/testnet/issues/1190)
- [x] [config/knex](https://github.com/interledger/testnet/issues/1190)
- [x] [cache - implement redis and in-memory also](https://github.com/interledger/testnet/issues/1191)
- [x] [all of the errors](https://github.com/interledger/testnet/issues/1192)
- [x] [middleware/errorHandler](https://github.com/interledger/testnet/issues/1192)
- [x] [tests/tables](https://github.com/interledger/testnet/issues/1193)
- [x] [tests/app](https://github.com/interledger/testnet/issues/1193)
- [x] [shared/model](https://github.com/interledger/testnet/issues/1194)
- [x] [utils - overlapping methods - use default response methods also for Wallet](https://github.com/interledger/testnet/issues/1195)
