### ISSUE TITLE
Dev Keys - Upload same key error

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1352]
**CONTEXT**

We get an 'Internal Server Error' for Uploading same Developer Keys. Only after Revoking the original key, you can upload the key again.

**Steps to reproduce**: 
- Go to Settings/Developer Keys
- Upload a key in the Developer Keys section for a Payment Pointer
- Try to upload the same key again to the same PP or a different one.

**Tasks**
- [ ] check if it is intended behaaviour to have unique Developer Keys
- [ ] check if one Payment Pointer can't have the same key multiple times, but different Payment Pointers can have the same Developer Key
- [ ] update the code accordingly to the above findings, with either fixing Internal Server Error, or appropiate Error Messages that can be displayed for the user
