### ISSUE TITLE
Grant revoke should be available for recuring payments

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1435]
## Context
We have a Revoke button on the Grants Details page, that should appear for recuring payments, for example One Click Buy Grant from rafiki.boutique.

## Todos
- [x] Check when does the Revoke button appear
- Make sure it appears for Recurring payments for example One Click buy setup, or Web Monetization Grants - NOT NEEDED ANYMORE
- Make sure Revoke button is not only appearing, but also working - NOT NEEDED ANYMORE

EDIT - after discussions with @mkurapov  we will change this story to the following:
- [x] Change condition of Revoke button appearing or not to only having finalizationReason === ISSUED, we don't need to check for state
- [x] When user tries Revoking a payment show a generic info message: 'Revoking a grant will prevent future payments from this client. You will need to give the client access again to allow them to initiate payments.'
