### ISSUE TITLE
Show Revoked grants also in Grants list

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1439]
## Context
We have a Revoke button appearing now for every grant in the list, that is finalized. Once you revoke the grant, it dissapears from the list. We would like to change this, and even after revoking a grant, to make sure it appears in the list.

## Todos
- [x] Check if it is possible to access from rafiki all types of grants, even Revoked ones
- [x] Change the get grants list with pagination, to include Revoked grants
- [x] Test Grants list, by adding a few grants - one time payments, and boutique one click payments - and revoke some of them, then make sure they appear correctly in the list
- [x] Make sure Grant details for a Revoked grant does not have Revoke button appear again.
- [ ] Change text to 'REVOKED' when finalization reason equals REVOKED for grant list and grant details (GrantDetails.tsx (32 row) and index.tsx (69 row)(from /grants)
