### ISSUE TITLE
Change usage of tooltips to Radix UI tooltips

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1492]
### Context

We are using in several places tooltips in the project.
We should use RADIX UI tooltips - for example new design Payment Pointer list page - Copy payment pointer tooltip

### Todos

- [ ] Change tooltips for send/receive on SEND page
- [ ] Change tooltip for PP name on Transaction page
- [ ] Identify other places where tooltips might be used and change them to RADIX UI
