### ISSUE TITLE
Cards in Test Wallet - card management

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1506]
### Context

We need to implement card management in test wallet.
Test wallet needs to be able to handle:
- card details view
- activate card -> activate card will be done inhouse at GateHub, we will not need to implement it
- freeze/unfreeze card
- pin code -> PIN code is 6 digits, we need view PIN and change PIN
- transactions view
- terminate card
- and maybe other functionalities also...TBD

We don't need to implement card issueing.
We need to implement the 2 dark/ligh modes for the new pages.
Designs are in Interledger figma.

### Todos

- [x] [implement reusable templates for card and buttons](https://github.com/interledger/testnet/issues/1522)
- [x] [implement card activation](https://github.com/interledger/testnet/issues/1511)
- [x] [implement card freeze/unfreeze](https://github.com/interledger/testnet/issues/1516)
- [x] [implement pin code functionalities](https://github.com/interledger/testnet/issues/1517)
- [x] [implement card details show/hide](https://github.com/interledger/testnet/issues/1515)
- [x] [implement card transactions](https://github.com/interledger/testnet/issues/1514)
- [x] [implement terminate card](https://github.com/interledger/testnet/issues/1518)
- [x] [improve passwords for security reasons](https://github.com/interledger/testnet/issues/1561)
- [x] [BE part of card management](https://github.com/interledger/testnet/issues/1620)
- [x] [WA to be $ilp.dev](https://github.com/interledger/testnet/issues/1624)
