### ISSUE TITLE
Test Wallet with Gatehub

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1509]
### Context

We need to switch out Rapyd to Gatehub Sandbox: 
- In order to do this we need to change some major thing in our code.
- Web Monetization Payment POointers will be removed from FE and BE, and asset scale 2 remains.
- GateHub can increase the request per minute for us if needed so we shouldn’t run into rate limiting issues.

Remove Rapyd KYC and use the GateHub KYC:
- We will not be able pre fill the fields for KYC since we are going to use the an iframe that points to GateHub - the users will have to fill in all the fields.
- We will have to check with GateHub if they can expose an API for us to approve the KYC directly or if it can be autoproved for the staging environment.

Bring back the withdraw functionality:
- During the Test Wallet’s redesign process it was decided the remove the withdraw functionality
- With GateHub, users will be able to withdraw money from their account
- The withdraw functionality will also use an iframe that points to GateHub

Replace Rapyd API with the GateHub API: 
- It will be a fresh start, we will be able to keep all the current user accounts for the Test Wallet, but not the balances for the test environment.

Setup an endpoint for GateHub webhooks:
 - We will have to check for which events we will receive webhooks from GateHub

### Todos

- [x] [The Web Monetization tab in the account page will be removed from the frontend, and we will no longer have wallet addresses and web monetization wallet addresses](https://github.com/interledger/testnet/issues/1507)
- [x] [Remove Rapyd KYC and use Gatehub KYC - no more prefill for the KYC fields - Gatehub will approve, use iframe](https://github.com/interledger/testnet/issues/1529)
- [x] [Withdraw functionallity should use an iframe pointing to Gatehub ](https://github.com/interledger/testnet/issues/1521)
- [x] [Add Money functionality should use an iframe pointing to GateHub](https://github.com/interledger/testnet/issues/1532)
- [x] [ILP Cards UI & Card management](https://github.com/interledger/testnet/issues/1506)
- [x] [Onboarding steps revisited for GateHub](https://github.com/interledger/testnet/issues/1535)
- [x] [Replace Rapyd with GateHub- BA](https://github.com/interledger/testnet/pull/1612)
- [x] [Add user to gateway -BA](https://github.com/interledger/testnet/pull/1623)

**Comment by Tymmmy** [comment]
Will close this story, Onboarding steps will be done soon
