### ISSUE TITLE
[GateHub] - Withdraw functionality - use Gatehub

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1521]
### Context

We curently use Rapyd withdraw functionalities.
We should use an iframe with Gatehub withdraw functionality.

### Todos

- [ ] remove functionality that uses Rapyd withdraw
- [ ] open an iframe when clicking on Withdraw
- [ ] use GateHub withdraw functionality in iframe
