### ISSUE TITLE
[GateHub] - Deposit functionality - use Gatehub 

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1532]
### Context

We curently use Rapyd deposit functionalities.
We should use an iframe with Gatehub deposit functionality.

### Todos

- [ ] remove functionality that uses Rapyd deposit
- [ ] open an iframe when clicking on Add Money
- [ ] use GateHub deposit functionality in iframe
