### ISSUE TITLE
[Cards] Card management in Test Wallet - Backend

### ISSUE THREAD

**Issue by sanducb** [interledger/testnet#1620]
### Context

We need to implement card management in test wallet backend.
Card activation will be handled by GateHub and cards will be locked by default.

### Todos

Test wallet backend needs to be able to handle:

- [x] https://github.com/interledger/testnet/issues/1626
- [x] https://github.com/interledger/testnet/issues/1628
- [x] https://github.com/interledger/testnet/issues/1627
- [x] https://github.com/interledger/testnet/issues/1629
- [x] https://github.com/interledger/testnet/issues/1630
- [x] https://github.com/interledger/testnet/issues/1660
- [x] https://github.com/interledger/testnet/issues/1667
- [x] https://github.com/interledger/testnet/issues/1714
- [x] https://github.com/interledger/testnet/issues/1712
- [x] https://github.com/interledger/testnet/issues/1670
- [x] #1673 TBD

**Comment by Tymmmy** [comment]
Will close the big issue, card session will be implemented in subtask
