### ISSUE TITLE
Add to passwords eye icon to view typed content

### ISSUE THREAD

**Issue by Tymmmy** [interledger/testnet#1639]
### Context

While registering or loging in, you might miss the password you set, or not set the same password for confirm password.
We should implement the eye icon to view the typed in content.

### Todos

- [x] add an eye icon to every password input, icon on the left, attached to input
- [x] when clicking on the eye, the typed in characters are visible
- [x] after clicking on the eye icon, the eye icon changes to a coressed out eye icon
- [x] when clicking on the crossed out eye icon, the characters will be not visible anymore

**Comment by Tymmmy** [comment]
There is forgotten password, and Change password as well - ChangePasswordForm and reset/[token]
